feat: 신고 상세
project-sulsul/SulSul-Admin pull request #7
Opened 2024-04-13 06:08 UTC by mopil

최선입니다. 가혹한 피드백 환영합니다.

2024-04-13 09:13 UTC, mopil commented
![image](https://github.com/project-sulsul/SulSul-Admin/assets/85692623/d4a94967-6a1a-42e3-aedf-6777149c3c12)

2024-04-13 09:13 UTC, mopil commented
![image](https://github.com/project-sulsul/SulSul-Admin/assets/85692623/f1083501-aa29-4e22-9f79-ced2167c5062)

2024-04-13 13:49 UTC, 5pponent requested changes

2024-04-13 13:49 UTC, 5pponent commented on src/pages/ReportDetailPage.jsx
> +        getFeedById({ targetId })
API 함수 호출할때 파라미터를
```javascript
getFeedById({ feedId: targetId })
```
형태로 넘겨야 될것같습니다.
{targetId}로 넘기면 getFeedById 함수에서는
```javascript
{ targetId: <targetId> }
```
로 받아서 아이디를 읽지 못해 API 호출 경로의 ID를 undefined로 내보냅니다.
그리고 타입이 comment일때도 분기 로직을 작성해야 할 것 같습니다

2024-04-13 13:57 UTC, mopil commented on src/pages/ReportDetailPage.jsx
> +        getFeedById({ targetId })
아하 글쿤요
근데 feed나 comment나 타입별 상관없이 결국 피드로 보내면 돼서 그냥 저렇게 분기 안 했슴다
(댓글이 피드상세에 포함되오ㅓ있음)

2024-04-13 14:07 UTC, 5pponent approved these changes
아주 좋습니다

2024-04-15 00:21 UTC, ez1n approved these changes
👍🏻

2024-04-15 00:21 UTC, ez1n commented on src/pages/ReportDetailPage.jsx
> +      if (detailData?.type === 'feed' || detailData?.type === 'comment') {
type을 상수로 빼서 사용하는 것도 좋을 것 같아요 :)

2024-04-15 00:21 UTC, ez1n commented on src/pages/ReportDetailPage.jsx
> +        });
업데이트 실패한 경우에도 모달창을 닫나요??

2024-04-15 00:21 UTC, ez1n commented on src/pages/ReportDetailPage.jsx
> +      />
필수는 아니지만 두 개의 액션중 하나가 '닫기'라면 CheckModal을 사용해도 될 것 좋을 것 같아요!

2024-04-16 04:41 UTC, mopil commented on src/pages/ReportDetailPage.jsx
> +        });
넹

2024-04-16 04:42 UTC, mopil commented on src/pages/ReportDetailPage.jsx
> +      />
checkModal은 뭔가영?

2024-04-20 09:57 UTC, mopil commented
일단 머지할게뇨

2024-04-20 09:58 UTC, merged